# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  gcp-gcr: circleci/gcp-gcr@0.7.1
# Orchestrate or schedule a set of jobs
workflows:
    jobs:
      build-and-push:
        executor: gcp-gcr/default
        steps:
          - checkout
          - gcp-gcr/gcr-auth
          # - gcp-gcr/build-image:
          #     image: orb-test
          #     registry-url: eu.gcr.io
          # - gcp-gcr/push-image:
          #     digest-path: /tmp/digest.txt
          #     image: orb-test
          #     registry-url: eu.gcr.io
          # - run:
          #     command: |
          #       echo "Digest is: $(</tmp/digest.txt)"
